# Generated by Django 4.2.7 on 2026-06-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamreward',
            name='marketer',
            field=models.ForeignKey(limit_choices_to={'role': 'team_leader'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_rewards', to='marketers.marketer'),
        ),
    ]
