# Generated by Django 4.2.7 on 2026-06-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketers', '0002_alter_teamreward_marketer'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_forced_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
