# Generated by Django 4.2.7 on 2026-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketers', '0003_marketerorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketerorderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
